Repository AY2425S1-CS2103T-W12-4/tp, pull requests merged in 2024-11, with the labels that each got.

#150 Make command fields optional
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddEventCommand.java
  src/main/java/seedu/address/logic/commands/AddPersonCommand.java
  src/main/java/seedu/address/logic/commands/EditEventCommand.java
  src/main/java/seedu/address/logic/commands/EditPersonCommand.java
  src/main/java/seedu/address/logic/parser/AddEventCommandParser.java
  src/main/java/seedu/address/logic/parser/AddPersonCommandParser.java
  src/main/java/seedu/address/logic/parser/EditEventCommandParser.java
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/model/event/UniqueEventList.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedEvent.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/card/EventCard.java
  src/main/java/seedu/address/ui/card/PersonCard.java
  src/main/java/seedu/address/ui/card/SimplifiedEventCard.java
  src/main/resources/view/DarkTheme.css
  src/test/java/seedu/address/logic/parser/AddPersonCommandParserTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/EventBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: type.Chore, priority.High

#217 Update UG images
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/add_event.png
  docs/images/add_person.png
  docs/images/clear_all.png
  docs/images/clear_all_confirmation.png
  docs/images/clear_event.png
  docs/images/clear_event_confirmation.png
  docs/images/delete_event.png
  docs/images/delete_person.png
  docs/images/delete_person_confirmation.png
  docs/images/edit_event.png
  docs/images/edit_person.png
  docs/images/filterBerniceYuResult.png
  docs/images/filterBetsyCroweResult.png
  docs/images/filterCelebrityResult.png
  docs/images/findHairOscarsResult.png
  docs/images/findJohnBerniceResult.png
  docs/images/findJohnBetsyResult.png
  docs/images/help-window.png
  docs/images/help.png
  docs/images/list_event.png
  docs/images/list_person.png
  docs/images/viewHairCutResult.png
  docs/images/viewJohnDoeResult.png
Labels: type.Chore, priority.High

#219 Edit titles to match functions
  docs/UserGuide.md
Labels: type.Chore, priority.High

#222 Edit tip box for delete event
  docs/UserGuide.md
Labels: type.Chore, priority.High

#223 Update architecture design and acknowledgements
  docs/DeveloperGuide.md
Labels: type.Chore, priority.High

#300 Fix DG typos
  docs/DeveloperGuide.md
Labels: type.Bug, type.DG

#292 Fix equals methods
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/model/person/Person.java
Labels: type.Bug

#293 Fix time parser
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/event/Time.java
  src/main/java/seedu/address/storage/JsonAdaptedTime.java
Labels: type.Bug

#323 Remove unnecessary terms and update glossary
  docs/DeveloperGuide.md
Labels: type.Chore, priority.High
