Repository AY2425S1-CS2103T-W12-4/tp, pull requests merged in 2024-10, with the labels that each got.

#29 Add AboutUs Information
  docs/AboutUs.md
Labels: priority.High

#38 Update site-wide settings
  docs/_config.yml
Labels: type.Chore, priority.High

#35 Update Target User Profile, Value Proposition and User Stories in DG
  docs/DeveloperGuide.md
Labels: type.Chore, priority.High

#36 Update README to match project
  README.md
  docs/images/Ui.png
Labels: type.Chore, priority.High

#45 Update dg nfr
  docs/DeveloperGuide.md
Labels: type.Chore, priority.High

#72 Add List Person Command
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/ListPersonCommand.java
  src/main/java/seedu/address/logic/commands/ViewContactCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ListCommandParser.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/ListPersonCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: type.Chore, priority.High

#66 Implement add event functionality
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AddContactCommand.java
  src/main/java/seedu/address/logic/commands/AddEventCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/event/UniqueEventList.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddContactCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddContactCommandTest.java
  src/test/java/seedu/address/logic/parser/AddContactCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: priority.High

#86 Add UI elements for Events
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddContactCommand.java
  src/main/java/seedu/address/logic/commands/AddEventCommand.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/ListPersonCommand.java
  src/main/java/seedu/address/logic/commands/ViewEventCommand.java
  src/main/java/seedu/address/logic/commands/ViewPersonCommand.java
  src/main/java/seedu/address/model/event/EventName.java
  src/main/java/seedu/address/model/event/Time.java
  src/main/java/seedu/address/model/event/Venue.java
  src/main/java/seedu/address/ui/CommandTabChange.java
  src/main/java/seedu/address/ui/EventCard.java
  src/main/java/seedu/address/ui/EventListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/EventListCard.fxml
  src/main/resources/view/EventListPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
Labels: type.Enhancement, priority.High

#99 Add view event message
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/ViewEventCommand.java
Labels: type.Bug, priority.High

#97 Add List Event Command
  src/main/java/seedu/address/logic/commands/ListEventCommand.java
  src/main/java/seedu/address/logic/parser/ListCommandParser.java
  src/main/java/seedu/address/model/Model.java
Labels: type.Chore, priority.High

#104 Fix add command and implement delete command
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddEventCommand.java
  src/main/java/seedu/address/logic/commands/AddPersonCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/DeleteEventCommand.java
  src/main/java/seedu/address/logic/commands/DeletePersonCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddEventCommandParser.java
  src/main/java/seedu/address/logic/parser/AddPersonCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteEventCommandParser.java
  src/main/java/seedu/address/logic/parser/DeletePersonCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddPersonCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddPersonCommandTest.java
  src/test/java/seedu/address/logic/commands/DeletePersonCommandTest.java
  src/test/java/seedu/address/logic/parser/AddPersonCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeletePersonCommandParserTest.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: priority.High

#106 Modify delete functionality and changes prefixes hehe
  src/main/java/seedu/address/logic/commands/DeleteEventCommand.java
  src/main/java/seedu/address/logic/commands/DeletePersonCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
Labels: priority.High

#111 Rename all instances of AddressBook in logs
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/LogsCenter.java
Labels: type.Bug, severity.Low

#113 Add clear event command
  src/main/java/seedu/address/logic/commands/ClearAllCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/ClearEventCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ClearCommandParser.java
  src/test/java/seedu/address/logic/commands/ClearAllCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearEventCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/testutil/TypicalAddressBook.java
  src/test/java/seedu/address/testutil/TypicalEvents.java
Labels: type.Story, priority.Medium

#115 Update sample data
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: type.Chore, priority.Medium

#122 Update UserGuide URL
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: type.Chore, priority.Medium, severity.Medium

#121 Update UserGuide.md
  docs/UserGuide.md
  docs/images/help.png
  docs/images/list_event.png
  docs/images/list_person.png
Labels: priority.High

#127 Update UG Summary, FAQ, Known Issues
  docs/UserGuide.md
Labels: type.Chore, priority.High

#133 Update clear commands in UG
  docs/UserGuide.md
  docs/images/clear_all.png
  docs/images/clear_event.png
Labels: type.Chore, priority.High

#141 Change POC list to set
  src/main/java/seedu/address/logic/commands/AddEventCommand.java
  src/main/java/seedu/address/logic/commands/EditEventCommand.java
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedEvent.java
  src/test/java/seedu/address/testutil/EventBuilder.java
Labels: type.Chore, priority.Medium, severity.Medium

#144 Change time variable to type LocalDateTime
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddEventCommand.java
  src/main/java/seedu/address/logic/commands/EditEventCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/event/EventName.java
  src/main/java/seedu/address/model/event/Time.java
  src/main/java/seedu/address/model/event/Venue.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedEvent.java
  src/main/java/seedu/address/storage/JsonAdaptedTime.java
  src/test/java/seedu/address/testutil/EventBuilder.java
  src/test/java/seedu/address/testutil/TypicalEvents.java
Labels: priority.High

#140 Update BetterModelClassDiagram
  docs/diagrams/BetterModelClassDiagram.puml
  docs/images/BetterModelClassDiagram.png
Labels: type.Chore, priority.High
